server:
  port: 8080
  servlet:
    path: /springboot
  tomcat:
    uri-encoding: UTF-8
age: 15
id: 18
spring:
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/jsp/
  thymeleaf:
    cache: false   #关闭缓存
    enabled: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-idle: 300
        max-active: 600
        max-wait: 300

  data:
    mongodb:
      host: localhost
      port: 27017
      database: test